version: '3.4'

services:
  authenticationapi:
    image: authenticationapi
    build:
      context: .
      dockerfile: src/Services/ALC.Authentication.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=sa_identity;Password=teste123;Database=authdb
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "dotnet", "ALC.Authentication.API.dll"]


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: sa_identity
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
