version: '3.4'

services:
  authentication_api:
    image: alc_eshop_auth_api
    build:
      context: .
      dockerfile: src/Services/ALC.Authentication.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=teste123;Database=authdb
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "dotnet", "ALC.Authentication.API.dll"]
  
  catalog_api:
    image: alc_eshop_catalog_api
    build:
      context: .
      dockerfile: src/Services/ALC.Catalog.API/Dockerfile
    ports:
      - "5100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=teste123;Database=catalogdb
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "dotnet", "ALC.Catalog.API.dll"]



  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
