@host = http://localhost:5042

GET {{host}}/weatherforecast/
Accept: application/json

###
POST {{host}}/api/authentication/registration/
{

}
Accept: application/json


###
POST {{host}}/api/authentication/Login
Accept: */*
Content-Type: application/json

{
    "email": "test",
    "password": "password"
}